{
    'name': 'Helpdesk Ticketing',
    'version': '16.0',
    'summary': 'Helpdesk Ticket Support, Management issue for customer or internal support',
    'author': 'github.com/zdni',
    'license': 'LGPL-3',
    'category': 'Helpdesk',
    'depends': [
        'base_setup',
        'digest',
        'schedule_task', 
        'department_detail', 
        'hr', 
        'hr_timesheet', 
        'product', 
        'stock', 
        'sale_management', 
        'purchase', 
        'purchase_request',
        'account',
        'portal',
        'mail',
        'sequence_reset_period',
        'web_tour',
        'web_kanban_gauge',
    ],
    'data': [
        'data/data.xml',
        'data/ir_sequence.xml',

        'security/ir.model.access.csv',

        'views/menu.xml',
        'views/helpdesk_configuration_views.xml',
        'views/helpdesk_ticket_views.xml',
    ],
    'auto_install': False,
    'application': False,
}